Repository 0x0I/container-file-prysm, pull requests merged in 2022-01, with the labels that each got.

#16 Adjusted genesis url
  scripts/prysm-helper.py
Labels: invalid

#18 add EXTRA_ARGS envvar entrypoint CMD extension interpretation
  Dockerfile
  README.md
  scripts/entrypoint.sh
Labels: enhancement

#19 release container infra for prysm v2.0.6
  version.txt
Labels: release
